name: Deploy to GitHub Pages
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
on:
  schedule:
    - cron: 0 2 * * 1-5
  push:
    branches:
      - master
      - release/*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: |
          npm ci
          npm i -g @angular/cli@15.2.0
      - run: |
          git config --global user.email "2469758101@qq.com"
          git config --global user.name "禾"
          ng deploy --no-silent
