name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  schedule:
    - cron: 0 2 * * 1-5
  push:
    branches:
      - master
      - release/*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.1

      - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm i -g @angular/cli@15.2.0
          npm ci
          ng lint
          ng deploy --name="禾" --email=2469758101@qq.com --no-silent

          # npm test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
          # npm run webdriver-update-ci
          # npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
