name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  schedule:
    - cron: 0 2 * * 1-5
  push:
    branches:
      - master
      - release/*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm ci
      - run: npm i -g @angular/cli@15.2.0
      - run: ng lint
      - run: ng deploy --name="禾" --email=2469758101@qq.com --no-silent
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}




